server:
  port: 8762
spring:
  application:
    name: microservice-discovery-eureka-client
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  #是否将自己的IP注册到Eureka Server中，默认false
  instance:
    prefer-ip-address: true
    #    心跳时间间隔
    lease-renewal-interval-in-seconds: 30
    #    服务失效时间
    lease-expiration-duration-in-seconds: 90
